# Generated by Django 6.1 on 2026-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='guest_session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
