# Generated by Django 6.1 on 2026-10-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_expires_at_cart_guest_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='guest_session_key',
        ),
    ]
