# Generated by Django 6.1 on 2026-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
    ]
