# Generated by Django 6.1 on 2026-10-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_cancellation_reason_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
