# Generated by Django 6.1 on 2026-09-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offers_ends_at',
            new_name='offer_ends_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='offers_start_at',
            new_name='offer_start_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
