# Generated by Django 6.1 on 2026-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_purchase_quantity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='max_purchase_quantity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
